# Generated by Django 4.2.27 on 2026-01-04 07:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('medico', '0004_alter_diagnostico_expediente_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='medico',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='pacientes', to='medico.medico'),
            preserve_default=False,
        ),
    ]
